WIP projects:ad713x_fmcz: fix data read bug
analogdevicesinc/no-OS pull request #1203
Opened 2022-01-11 13:22 UTC by adrimbarean

The projct was returning always the same sample of data because the one
of the ADCs was used in a reserved mode of operation. The chip can only
function as a master on the data bus (generate SPI clock and ODR) or a
slave (accept SPI clock and ODR). The chip was used instead to generate
ODR, but accept the SPI clock which cannot work properly.

To accomodate this use a an AXI PWM generator to generate ODR at a
specified rate for both devices. Note: the ODR signal must be present
before chip initialization.

Signed-off-by: Andrei Drimbarean <Andrei.Drimbarean@analog.com>

PR is to be merged after the HDL changes propagate to master.

2022-01-11 15:44 UTC, dbogdan approved these changes

2022-01-11 16:42 UTC, mchindri approved these changes

2022-01-11 16:42 UTC, mchindri commented on projects/ad713x_fmcz/src/ad713x_fmc.c
> +	uint32_t spi_eng_dma_flg = 6;
Is there any define for 6?

2022-01-11 17:20 UTC, amiclaus reviewed
`error: 'XPAR_ODR_GENERATOR_BASEADDR' undeclared (first use in this function); did you mean 'XPAR_DDR_MEM_BASEADDR'?`

`error: 'XPAR_AXI_AD7134_CLKGEN_BASEADDR' undeclared (first use in this function); did you mean 'XPAR_AXI_SDP_CLKGEN_BASEADDR'?`

Do we require a hdl update on the CI side for this?

2022-01-12 06:43 UTC, adrimbarean commented
> Do we require a hdl update on the CI side for this?

Precisely. The work is done, just needs to be merged to master on the HDL side before we can merge this.

2022-01-12 06:44 UTC, adrimbarean commented on projects/ad713x_fmcz/src/ad713x_fmc.c
> +	uint32_t spi_eng_dma_flg = 6;
Will do.

2022-01-12 07:34 UTC, amiclaus approved these changes

2022-01-12 10:03 UTC, adrimbarean commented
V1:
 - add partial reporting flag to AXI DMAC driver;
 - `uint32_t spi_eng_dma_flg = 6;` => `uint32_t spi_eng_dma_flg = DMA_LAST | DMA_PARTIAL_REPORTING_EN;`

2022-01-12 11:19 UTC, adrimbarean commented
V2:
 - rebase on latest master

2022-01-12 12:10 UTC, adrimbarean commented
V3:
 - include `axi_dmac.h` in main source to use DMA flags.

2022-01-12 16:26 UTC, amiclaus commented on projects/ad713x_fmcz/src/parameters.h
> -#define SPI_ENGINE_RX_ADDR		0x800000
it looks like these defines are still used here :
https://github.com/analogdevicesinc/no-OS/blob/bfb5fecff0b18a7494bd0db0e7fd77467d8eae5e/projects/ad713x_fmcz/src/ad713x_fmc.c#L300-L302

2022-01-13 07:40 UTC, amiclaus requested changes
https://github.com/analogdevicesinc/no-OS/pull/1203/files#diff-90539af6fbd9d1894cf26ba395029f0900135ac1943c5b7af3829289d7d4778cL81-L83

it looks like these defines are still used here :
https://github.com/analogdevicesinc/no-OS/blob/bfb5fecff0b18a7494bd0db0e7fd77467d8eae5e/projects/ad713x_fmcz/src/ad713x_fmc.c#L300-L302

2022-01-14 11:38 UTC, adrimbarean commented
V4:
 - fix IIO build;
 - rebase on latest master.

2022-01-17 06:38 UTC, amiclaus requested changes

2022-01-17 06:38 UTC, amiclaus commented on projects/ad713x_fmcz/.Xil/-20668-ADRIMBAR-L02/system.bda
> +﻿<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
I believe this file was added by mistake 😄. Maybe we can add `.Xil` folder to gitignore.

2022-01-17 06:38 UTC, amiclaus commented on drivers/axi_core/axi_dmac/axi_dmac.h
> +	DMA_PARTIAL_REPORTING_EN = 4
nit: I think the commit description `No functional changes` is not quite correct :)

2022-01-17 12:11 UTC, adrimbarean commented
V5:
 - removed unnecessary file;
 - add different commit description for the second commit.

2022-01-17 12:36 UTC, amiclaus approved these changes

2022-01-19 08:19 UTC, merged