adxrs453: Fix value returned by register read
analogdevicesinc/no-OS pull request #1297
Opened 2022-03-16 02:43 UTC by ryandavid

Value returned by register read was actually the result from the previous command.

Issue is repeatable:
 - Attempt to read the part ID register (assuming it wasn't the last register read since power on)
 - Result back will not match.
 - Subsequent read of the part ID register will return the correct result, but its really the value from the previous request.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/1046093/158505931-bd2023f3-eb10-4a53-87e0-8d49ce195323.png">

2022-03-16 02:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/analogdevicesinc/no-OS?pullRequest=1297) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/analogdevicesinc/no-OS?pullRequest=1297) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/analogdevicesinc/no-OS?pullRequest=1297) it.</sub>

2022-03-16 07:29 UTC, amiclaus approved these changes

2022-03-16 07:32 UTC, buha commented
Good catch.
But could you please put the text from the PR description in the commit message ?
And perhaps amend with `git --amend -s` and then `git push --force` ?

2022-03-16 07:36 UTC, amiclaus requested changes
> Good catch. But could you please put the text from the PR description in the commit message ? And perhaps amend with `git --amend -s` and then `git push --force` ?



> Good catch. But could you please put the text from the PR description in the commit message ? And perhaps amend with `git --amend -s` and then `git push --force` ?

Indeed, @buha  is right. Also please make sure that the commit contains the `Signed-off by:` tag

2022-03-28 09:04 UTC, amiclaus reviewed
@ryandavid any feedback on the requested changes?

2022-04-04 12:12 UTC, amiclaus reviewed
@ryandavid due to long response time and wanting to reduce the nr. of PR opened on the no-OS repository, I created a PR with the required changes here:  https://github.com/analogdevicesinc/no-OS/pull/1315

On that note, closing this PR.

2022-04-04 12:12 UTC, closed without merging