ad4110:src.mk Add no_os_util.c to sources
analogdevicesinc/no-OS pull request #1678
Opened 2023-03-02 13:41 UTC by danmois

Add no_os_util.c to sources. Required after the addition of timestamps.

2023-03-02 14:04 UTC, buha commented
we should add builds.json CI configuration for this project

2023-03-02 14:56 UTC, amiclaus approved these changes

2023-03-02 15:24 UTC, buha requested changes
builds.json

2023-03-03 10:06 UTC, amiclaus reviewed
v2:
- add builds.json

2023-03-03 10:47 UTC, buha approved these changes

2023-03-03 15:15 UTC, amiclaus approved these changes

2023-03-08 08:27 UTC, merged