drivers: frequency: ltc6953: Add status functions
analogdevicesinc/no-OS pull request #1796
Opened 2023-06-05 03:58 UTC by MarielTinaco

Added additional status functions to cover remaining register fields of LTC6953

2023-06-05 06:37 UTC, jsanbuen requested changes

2023-06-05 06:37 UTC, jsanbuen commented on drivers/frequency/ltc6953/ltc6953.c
> +
remove extra space.

2023-06-05 06:37 UTC, jsanbuen commented on drivers/frequency/ltc6953/ltc6953.c
> +
remove extra space.

2023-06-05 06:37 UTC, jsanbuen commented on drivers/frequency/ltc6953/ltc6953.c
> +	if (status > 1)
INVSTAT is single bit field, so this can be changed to bool instead. Doing so will remove the need to check for status.

2023-06-05 06:37 UTC, jsanbuen commented on drivers/frequency/ltc6953/ltc6953.c
> +int ltc6953_get_invstat(struct ltc6953_dev *dev, uint8_t *status)
INVSTAT is single bit field, so this can be changed to bool instead. Doing so will remove the need to check for status.

2023-06-05 06:37 UTC, jsanbuen commented on drivers/frequency/ltc6953/ltc6953.c
> +
remove extra space.

2023-06-05 06:37 UTC, jsanbuen commented on drivers/frequency/ltc6953/ltc6953.h
> +int ltc6953_get_invstat(struct ltc6953_dev *dev, uint8_t *status);
change uint8_t to bool in relation to previous INVSTAT comments.

2023-06-05 06:37 UTC, jsanbuen commented on drivers/frequency/ltc6953/ltc6953.h
> +int ltc6953_set_invstat(struct ltc6953_dev *dev, uint8_t status);
change uint8_t to bool in relation to previous INVSTAT comments.

2023-06-05 08:05 UTC, jsanbuen requested changes

2023-06-05 08:05 UTC, jsanbuen commented on drivers/frequency/ltc6953/ltc6953.c
> +	return ltc6953_update(dev, LTC6953_REG_STAT, LTC6953_X_STAT_MSK,
Add checking to make sure that "x" should be within the limits (6 bits, max possible value is 63). Any other value passed should return -EINVAL.

2023-06-05 18:13 UTC, jsanbuen approved these changes

2023-06-06 05:49 UTC, CiprianRegus approved these changes

2023-06-06 05:52 UTC, CiprianRegus commented
Looks good. My only request would be to add a commit description which provides some details about what is done here.

2023-06-07 07:07 UTC, danmois commented on drivers/frequency/ltc6953/ltc6953.c
> + * @param is_ok - Container variable for VCO input status.
Maybe specifying what 0 and 1 mean in the context would be beneficial. This is valid also for the status parameter of the next function (0 OK or not OK).

2023-06-08 07:35 UTC, amiclaus commented on drivers/frequency/ltc6953/ltc6953.c
> - * @param rev - container variable for Revision number.
unrelated change.

2023-06-08 07:35 UTC, amiclaus commented on drivers/frequency/ltc6953/ltc6953.c
> -
ditto.

2023-06-08 07:35 UTC, amiclaus commented on drivers/frequency/ltc6953/ltc6953.c
> -
ditto.

2023-06-08 07:35 UTC, amiclaus commented on drivers/frequency/ltc6953/ltc6953.h
> -#define LTC6953_STAT_OUT_MSK		NO_OS_GENMASK(6, 0)
it this renaming required? if so, move it to a separate commit.

2023-06-09 08:04 UTC, merged