parameters.h  Update defines to match the latest HDL
analogdevicesinc/no-OS pull request #1857
Opened 2023-08-08 12:37 UTC by danmois

Update AXI SPI related & other defines in no-OS to match the latest HDL.

HDL introduced a new SPI hierarchy which is reflected in the macros generated in xparameters.h from .xsa.

For example, what used to be called before XPAR_CN0561_SPI_AXI_BASEADDR is now called XPAR_SPI_CN0561_SPI_CN0561_AXI_REGMAP_BASEADDR.

Git blame in hdl:
https://github.com/analogdevicesinc/hdl/commit/553774319a12254bfd5792b9869234d36345afd9#diff-bc564d9ee1a3935befd0bb57534492fed38a6c78dd280fb07219510fc886d980R73

2023-08-08 12:40 UTC, amiclaus approved these changes
looks good, let's wait for the build to finish successfully for the Xilinx platform.

2023-08-08 14:16 UTC, amiclaus requested changes
re-triggered the Xilinx build since there are still some issues.

2023-08-10 10:20 UTC, amiclaus commented on projects/ad9361/src/parameters.h
> +#if defined(XPAR_AXI_DDR_CNTRL_BASEADDR)
this looks odd, and not very deductive. If you need to differentiate between boards you should go for the approach:
https://github.com/analogdevicesinc/no-OS/blob/6d75bc376eb7f1a4fd992cac75a7e33c0c89e37e/projects/ad9361/builds.json#L60

2023-08-10 10:20 UTC, amiclaus commented on projects/ad7768-evb/src/ad7768_evb.c
> -	axi_gpio_init.type = GPIO_PL;
I wouldn't remove this code yet. Rather check inline for the definition of `GPIO_STATUS_DEVICE_ID` and only if available perfrom these status checks.

2023-08-10 13:29 UTC, dbogdan approved these changes

2023-08-10 13:39 UTC, merged