Staging/cherrypick
analogdevicesinc/no-OS pull request #1890
Opened 2023-09-07 09:31 UTC by AAndrisa

## Pull Request Description

Please replace this with a detailed description and motivation of the changes. 
You can tick the checkboxes below with an 'x' between square brackets or just check them after publishing the PR. 
If this PR contains a breaking change, list dependent PRs and try to push all related PRs at the same time.

## PR Type
- [x] Bug fix (change that fixes an issue)
- [x] New feature (change that adds new functionality)
- [ ] Breaking change (has dependencies in other repos or will cause CI to fail)

## PR Checklist
- [x] I have followed the [Coding style guidelines](http://analogdevicesinc.github.io/no-OS/drivers_guide.html#coding-style)
- [x] I have performed a self-review of the changes
- [x] I have commented my code, at least hard-to-understand parts
- [ ] I have build all projects affected by the changes in this PR
- [ ] I have tested in hardware affected projects, at the relevant boards
- [x] I have signed off all commits from this PR
- [ ] I have updated the documentation (wiki pages, ReadMe etc), if applies

2023-09-07 09:33 UTC, amiclaus approved these changes

2023-09-07 09:44 UTC, SRaus requested changes
Please update PR description -  do not let the default one.
Also, whenever you do cherry-picks, it is recommended to use "-x" parameter (see documentation [here](https://git-scm.com/docs/git-cherry-pick))

2023-09-07 13:25 UTC, AAndrisa commented
V2: cherry-picked the commits with the -x option

2023-09-07 18:47 UTC, SRaus approved these changes

2023-09-08 08:07 UTC, buha approved these changes

2023-09-08 08:09 UTC, merged