Integrate blacklist in no-os build
analogdevicesinc/no-OS pull request #2092
Opened 2024-02-01 13:49 UTC by AAndrisa

## Pull Request Description

Some projects from hdl are failing, in order to ignore this failing projects on hdl side a 'blacklist' was created.
This list is now processed in no-os to skip the build for those projects as well.
The build branch needs to be exported because of the changes regarding blacklist integration.

## PR Type
- [ ] Bug fix (change that fixes an issue)
- [x] New feature (change that adds new functionality)
- [x] Breaking change (has dependencies in other repos or will cause CI to fail)

## PR Checklist
- [x] I have followed the [Coding style guidelines](http://analogdevicesinc.github.io/no-OS/drivers_guide.html#coding-style)
- [x] I have performed a self-review of the changes
- [ ] I have commented my code, at least hard-to-understand parts
- [x] I have build all projects affected by the changes in this PR
- [ ] I have tested in hardware affected projects, at the relevant boards
- [x] I have signed off all commits from this PR
- [ ] I have updated the documentation (wiki pages, ReadMe etc), if applies

2024-02-01 14:03 UTC, AAndrisa commented
v1: add blacklist initialization in configure_and_download_all_hw function

2024-02-01 15:36 UTC, SRaus requested changes

2024-02-01 15:36 UTC, SRaus commented on tools/scripts/build_projects.py
> +	for line in file.readlines():
Add  also a condition for empty lines, beside the commented ones.

2024-02-02 09:40 UTC, AAndrisa commented
v2: added check for empty lines

2024-02-02 10:20 UTC, SRaus approved these changes

2024-02-02 10:20 UTC, AAndrisa commented
v3: change comments check in blacklist file

2024-02-02 10:45 UTC, rbolboac approved these changes

2024-02-02 11:34 UTC, merged