Add driver support for LT8491
analogdevicesinc/no-OS pull request #2330
Opened 2024-10-09 01:09 UTC by jemfgeronimo

## Pull Request Description

The LT8491 is a buck-boost switching regulator battery charger that implements a
constant-current constant-voltage (CCCV) charging profile used for most battery
types, including sealed lead-acid (SLA), flooded, gel and lithium-ion.

The device operates from input voltages above, below or equal to the output
voltage and can be powered by a solar panel or a DC power supply. On-chip logic
provides automatic maximum power point tracking (MPPT) for solar powered
applications. The LT8491 can perform automatic temperature compensation by
sensing an external thermistor thermally coupled to the battery. The STATUS pin
can be used to drive an LED indicator lamp. The device is available in a low
profile (0.75mm) 7mm x 11mm 64-lead QFN package.

The driver also supports MAX31828 and MAX31829.

## PR Type
- [ ] Bug fix (change that fixes an issue)
- [x] New feature (change that adds new functionality)
- [ ] Breaking change (has dependencies in other repos or will cause CI to fail)

## PR Checklist
- [x] I have followed the [Coding style guidelines](http://analogdevicesinc.github.io/no-OS/drivers_guide.html#coding-style)
- [x] I have performed a self-review of the changes
- [x] I have commented my code, at least hard-to-understand parts
- [ ] I have build all projects affected by the changes in this PR
- [x] I have tested in hardware affected projects, at the relevant boards
- [x] I have signed off all commits from this PR
- [ ] I have updated the documentation (wiki pages, ReadMe etc), if applies

2024-10-10 07:49 UTC, CiprianRegus requested changes

2024-10-10 07:49 UTC, CiprianRegus commented on drivers/power/lt8491/lt8491.c
> +/******************************************************************************/
Please remove these comments.

2024-10-10 07:49 UTC, CiprianRegus commented on drivers/power/lt8491/lt8491.c
> +int lt8491_read_charging_stage(struct lt8491_device *dev, int32_t *charval)
You could just use the enum values in an application directly. Why is there a need to assign a character to them?

2024-10-10 07:49 UTC, CiprianRegus commented on drivers/power/lt8491/lt8491.h
> +struct lt8491_device {
we usually name these `_desc`. Can you please do the same here?

2024-10-10 07:49 UTC, CiprianRegus commented on drivers/power/lt8491/iio_lt8491.c
> +	return lt8491_reg_read(dev->dev, (uint8_t)reg, (uint16_t*)readval,
You will have to use a `uint16_t *` variable in order to read the value. Otherwise the result will be different depending on CPU endianess.

2024-10-10 07:49 UTC, CiprianRegus commented on drivers/power/lt8491/iio_lt8491.c
> +	if (ret)
You can remove this, as ret will always be 0.

2024-10-10 07:49 UTC, CiprianRegus commented on drivers/power/lt8491/iio_lt8491.c
> +};
These should all be debug attributes. "Standard" IIO attibutes are documented on the IIO ABI page https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-bus-iio and we should strive to use the same ones for no-OS too. Here is the list of attributes supported by no-os https://github.com/analogdevicesinc/no-OS/blob/main/iio/iio.c#L109 and a driver which uses both types https://github.com/analogdevicesinc/no-OS/blob/main/drivers/imu/iio_adis.c

2024-10-15 04:50 UTC, jemfgeronimo commented
V2
- moved global attributes to debug attributes
- some global attributes are now iio channel attributes
- renamed `lt8491_device` to `lt8491_desc`
- removed big comments, e.g., `/*Macros and Constants Definitions*/`
- modified `lt8491_read_charging_stage` to get `int` rather than `char`

2024-10-25 06:03 UTC, kister-jimenez reviewed
Only minor comments that needs to be addressed. Other than that, looks good to me.

2024-10-28 06:53 UTC, jemfgeronimo commented on projects/dc2703a/README.rst
> +Li-Ion batteries.
Will this suffice?
```suggestion
The DC2703A-A-KIT houses the DC2703A (LT8491 demo board). They provide a high
performance buck-boost battery charger converter with an I2C interface for a
microcontroller host. The LT8491 implements a maximum power point tracking
(MPPT) function and flexible charging profiles, suitable for most battery types
such as flooded and sealed lead acid batteries and Li-Ion batteries.
```

2024-10-30 08:08 UTC, CiprianRegus submitted a review, later dismissed
No-OS has recently transitioned to a BSD 3 clause license (from ADI BSD). Please update the license headers for all files. Otherwise, it looks good.

The new license: https://github.com/analogdevicesinc/no-OS/blob/main/LICENSE_BSD

2024-10-30 08:38 UTC, jemfgeronimo commented
V3
- improved `Overview` in `projects/dc2703a/README.rst`
- fixed typo in `projects/dc2703a/src/platform/maxim/main.c`
- updated license headers to `BSD 3` clause license (from `ADI BSD`)

2024-10-30 08:41 UTC, kister-jimenez approved these changes

2024-10-30 08:51 UTC, CiprianRegus approved these changes

2024-10-30 09:26 UTC, merged