Add support for ltc7871
analogdevicesinc/no-OS pull request #2402
Opened 2024-12-18 03:37 UTC by AAbacan2

## Pull Request Description

Please replace this with a detailed description and motivation of the changes. 
You can tick the checkboxes below with an 'x' between square brackets or just check them after publishing the PR. 
If this PR contains a breaking change, list dependent PRs and try to push all related PRs at the same time.

## PR Type
- [ ] Bug fix (change that fixes an issue)
- [ ] New feature (change that adds new functionality)
- [ ] Breaking change (has dependencies in other repos or will cause CI to fail)

## PR Checklist
- [ ] I have followed the [Coding style guidelines](http://analogdevicesinc.github.io/no-OS/drivers_guide.html#coding-style)
- [ ] I have performed a self-review of the changes
- [x] I have commented my code, at least hard-to-understand parts
- [ ] I have build all projects affected by the changes in this PR
- [ ] I have tested in hardware affected projects, at the relevant boards
- [x] I have signed off all commits from this PR
- [x] I have updated the documentation (wiki pages, ReadMe etc), if applies

2024-12-18 03:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/analogdevicesinc/no-OS?pullRequest=2402) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/analogdevicesinc/no-OS?pullRequest=2402) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/analogdevicesinc/no-OS?pullRequest=2402) it.</sub>

2024-12-18 04:24 UTC, kister-jimenez commented
/AzurePipelines run

2024-12-19 08:22 UTC, kister-jimenez commented
/AzurePipelines run

2025-01-08 03:13 UTC, kister-jimenez commented
/AzurePipelines run

2025-01-13 02:45 UTC, kister-jimenez commented
/AzurePipelines run

2025-01-17 08:57 UTC, kister-jimenez commented
/AzurePipelines run

2025-01-22 09:46 UTC, buha requested changes
It looks good but you'll have to update the project to the new project infrastructure.

Here's the PR with the changes with 3 modified projects as example: https://github.com/analogdevicesinc/no-OS/pull/2412

And here's a pending PR where I gave feedback with pretty much that needs to be changed, same applies to your PR.
https://github.com/analogdevicesinc/no-OS/pull/2411

2025-01-24 03:29 UTC, kister-jimenez commented
/AzurePipelines run

2025-01-24 06:19 UTC, kister-jimenez commented
/AzurePipelines run

2025-01-27 08:34 UTC, CiprianRegus commented on drivers/power/ltc7871/iio_ltc7871.c
> +	no_os_free(desc->iio_dev->channels);
This array is statically allocated

2025-01-27 13:11 UTC, buha commented on projects/ltc7871/src/examples/basic/basic_example.c
> +		//TODO:
remove this

2025-01-27 13:12 UTC, buha commented on projects/ltc7871/src/platform/maxim/parameters.h
> +#ifdef IIO_SUPPORT
i think the ifdef is not needed, you may delete it

2025-01-27 13:13 UTC, buha commented on projects/ltc7871/README.rst
> +	BASIC_EXAMPLE = y
please update this, this is not true anymore

2025-01-27 13:13 UTC, buha commented on projects/ltc7871/README.rst
> +        BASIC_EXAMPLE = n
same here

2025-01-27 13:14 UTC, buha commented on projects/ltc7871/README.rst
> +	make PLATFORM=maxim TARGET=max32690 run
maybe split this in two, dont build and run on the same line, it works but may confuse readers

2025-01-28 09:10 UTC, AAbacan2 commented
changes:
* iio_ltc7871.c - remove no_os_free(desc->iio_dev->channels) 
* basic_example.c - remove TODO
* maxim/parameters.h - remove ifdef for iio support
* ltc7871/README.rst - remove references to outdated project infrastructure and update  build commands

2025-01-31 15:02 UTC, dbogdan approved these changes

2025-01-31 15:06 UTC, merged