iio:iio_ad7124: initial commit
analogdevicesinc/no-OS pull request #863
Opened 2020-12-10 10:51 UTC by adrimbarean

Add AD7124 IIO driver. Closely resembles the Linux driver to maintain
compatibility with tools that use it:
https://github.com/analogdevicesinc/linux/blob/master/drivers/iio/adc/ad7124.c

Signed-off-by: Andrei Drimbarean <Andrei.Drimbarean@analog.com>

2020-12-10 11:29 UTC, mchindri requested changes

2020-12-10 11:29 UTC, mchindri commented on iio/iio_ad7124/iio_ad7124.c
> +int32_t iio_ad7124_init(struct iio_ad7124_desc **desc,
This function is unnecesary.
Create a structure like: https://github.com/analogdevicesinc/no-OS/blob/5a93b5a6e9fb132fd92a1bef0050eb27d5e32aa8/iio/iio_demo/iio_demo_dev.h#L145

2020-12-10 11:29 UTC, mchindri commented on iio/iio_ad7124/iio_ad7124.c
> +static ssize_t iio_ad7124_transfer_dev_to_mem(void *iio_inst,
Did you tried: https://github.com/analogdevicesinc/no-OS/blob/5a93b5a6e9fb132fd92a1bef0050eb27d5e32aa8/iio/iio_demo/iio_demo_dev.h#L151

2020-12-10 11:29 UTC, mchindri commented on iio/iio_ad7124/iio_ad7124.c
> +static ssize_t iio_ad7124_transfer_dev_to_mem(void *iio_inst,
and read_dev functions

2020-12-10 11:29 UTC, mchindri commented on iio/iio_ad7124/iio_ad7124.c
> +		.scan_type = NULL, \
You should set a scan_type

2020-12-10 11:46 UTC, cristiantpop commented on iio/iio_ad7124/iio_ad7124.c
> +	ldesc->iio_ad7124_device->num_ch = 8;
ARRAY_SIZE(ad7124_channels)

2020-12-10 11:52 UTC, cristiantpop commented on iio/iio_ad7124/iio_ad7124.c
> +
extra line

2020-12-10 11:53 UTC, cristiantpop commented on iio/iio_ad7124/iio_ad7124.c
> +	ad7124_read_register(desc, &desc->regs[AD7124_ERR_REG]);
Check return value for function calls

2020-12-10 11:54 UTC, cristiantpop commented on iio/iio_ad7124/iio_ad7124.c
> +	ad7124_8pmdz_fclk_logic_get(dev, &f_clk);
Check return

2021-01-06 07:20 UTC, adrimbarean commented
V1: 
 - check return values of functions;
 - remove extra lines;
 - set default scan type for channels;
 - avoid init function by making a structure instance directly;
 - use iio_app following the iio_demo model;
 - update driver according to new library.

2021-01-06 08:32 UTC, dbogdan approved these changes

2021-01-06 13:09 UTC, mchindri commented on iio/iio_ad7124/iio_ad7124.c
> +static ssize_t ad1724_iio_read_offset_chan(void *device, char *buf, size_t len,
typo in name: ad7124

2021-01-06 13:09 UTC, mchindri commented on iio/iio_ad7124/iio_ad7124.c
> +	value = desc->regs[(AD7124_OFFS0_REG + channel->ch_num)].value;
I think fields from inside desc should pe only accesed inside the drivere that created that structure. So my approach will be to create in the driver a function ad7124_read_offset_chan . 
Same for other the remaining functions

2021-01-06 13:12 UTC, mchindri commented on iio/iio_ad7124/iio_ad7124.c
> +	value = desc->regs[(AD7124_OFFS0_REG + channel->ch_num)].value;
And then you can do a switch calling that function like this: https://github.com/analogdevicesinc/no-OS/blob/05cd411971cb9368179cdadbf695d6a95f404ba3/drivers/platform/aducm3029/iio_aducm3029.c#L222

2021-01-06 13:51 UTC, mchindri commented
Move iio files in drivers/adc/ad7124
https://github.com/analogdevicesinc/no-OS/pull/889#discussion_r552625001

2021-01-07 07:37 UTC, adrimbarean commented on iio/iio_ad7124/iio_ad7124.c
> +static ssize_t ad1724_iio_read_offset_chan(void *device, char *buf, size_t len,
Will do.

2021-01-07 07:37 UTC, adrimbarean commented on iio/iio_ad7124/iio_ad7124.c
> +	.sign = 'i',
Will fix.

2021-01-07 09:58 UTC, adrimbarean commented on iio/iio_ad7124/iio_ad7124.c
> +
I can do this, but it seems that the general rule is to define variables in a source file and share it with extern in header. Do we want to make our own rule?

2021-01-11 11:02 UTC, adrimbarean commented
V2:
 - correct scan_type sign value;
 - correct ad1724 -> ad7124 typo;
 - implement requested changes in the device driver and act accordingly: https://github.com/analogdevicesinc/no-OS/pull/904

2021-01-12 06:20 UTC, mchindri approved these changes
Beside the iio definitions are in the .c file, LGTM

2021-01-12 06:25 UTC, dbogdan commented
Where was ad7124_read_register_wrap() implemented? I think Pipelines' complaints are valid.

2021-01-12 06:57 UTC, mchindri commented
> Where was ad7124_read/write_register_wrap() implemented? I think Pipelines' complaints are valid.

In #904. Maybe that Pr should be merged first or add it as a commit here

2021-01-12 11:15 UTC, adrimbarean commented
V3:
 - update the code to work with new ad7124 driver https://github.com/analogdevicesinc/no-OS/pull/904;

2021-01-12 11:34 UTC, adrimbarean commented
V4:
 - fix astyle.

2021-01-13 08:23 UTC, merged